---
title: "Conclusion"
output: html_document
---

Using the predictors at baseline on the day of discharge, I use the method of autonomic selection with backward selection to build a prediction model with negative binomial regression for the non-suicidal injury at 6 months and 12 months after discharge. For both models, we see outliers, but they do not have a strong influence. For predicting the non-suicidal injury at 6 months, we see that suicidal ideation (SIQ), sex, and baseline non-suicidal injury show statistically significant in my model. With increase suicidal ideation, increase baseline non-suicidal injury, and female sex, there is a higher risk of non-suicidal injury at 6 months. These correlated with what we see in clinical practice and from the literature on the risk of non-suicidal injuries[1-6]. For the non-suicidal injury at 12 months, we see that sex, baseline non-suicidal injury and non-suicidal injury at 6 months show statistically significant in my model. With female sex, increase baseline non-suicidal injury, and non-suicidal injury at 6 months, there is a higher risk of non-suicidal injury at 12 months. The higher risk of the female sex correlates with the literature[1-6]. However, like prior research, we see differing patterns of stability and frequency of NSSI[2]. In addition, this result did not show any significance for scales in emotional regulation and emotional reactivity, which are risk factors for NSSI[6]. 
This analysis is successful that we see the previous non-suicidal injury and the female sex still plays the most important role in predicting the risk of future non-suicidal injury. In addition, we did not see the risk with the emotional regulation and reactivity as we predicted. 
If I had more time, I would like to do a group-based analysis on trying to predict the trajectories of non-suicidal injury. For clinicians, it is often hard to estimate the risk for these adolescent patients. If we have a more objective tool to help with predicting the trajectories of non-suicidal injury, we can have a better estimate of the risk for these patients.