---
title: "Introduction"
---

  This is a dataset collected from MGH psychiatric ward. The data consists of 211 adolescents (aged 13-18 years old) admitted to the psychiatric ward (with no exclusion on any diagnosis). The data is collected prospectively with a baseline at discharge from the hospital. The patients were followed up at 6 months and 12 months after discharge. At the time of discharge (baseline), 6 months, and 12 months, the number of non-suicidal injuries over the past 30 days was collected. At baseline, possible predictors and covariates related to non-suicidal injury were collected. The CDI-2 scale was used for the depression scale. The SIQ-Jr scale was used for suicidal ideation. For evaluating emotional reactivity and regulation, DERS, DANVA (including adult face and children face), and ERS were collected at baseline. The baseline demographics of the patients were also collected. From these collected data, I want to find baseline predictors to predict non-suicidal injury at 6 months and at 12 months.

## Hypthosis:
Emotional dysregulation and reactivity at discharge predict the risk of non-suicidal injury after discharge. 